INSERT INTO public.utilisateurs (id, nom, prenom, email, motdepasse, role) VALUES (2, 'Zappelini', 'Amelia', 'ameliazap@gmail.com', '1234', 'user');
INSERT INTO public.utilisateurs (id, nom, prenom, email, motdepasse, role) VALUES (3, 'Bah', 'Habib', 'habibbah@gmail.com', '1234', 'user');
INSERT INTO public.utilisateurs (id, nom, prenom, email, motdepasse, role) VALUES (4, 'SBah', 'SHabib', 'habib@admin.fr', '1111', 'admin');
INSERT INTO public.utilisateurs (id, nom, prenom, email, motdepasse, role) VALUES (5, 'SBah', 'SHabib', 'habib@admin.fr', '1111', 'admin');
INSERT INTO public.utilisateurs (id, nom, prenom, email, motdepasse, role) VALUES (6, 'zappelini', 'Amelia', 'ameliazapp@hotmail.fr', '1234', 'user');
INSERT INTO public.utilisateurs (id, nom, prenom, email, motdepasse, role) VALUES (7, 'Cook', 'Lyam', 'lyamcook@gmail.com', '1234', 'user');
INSERT INTO public.utilisateurs (id, nom, prenom, email, motdepasse, role) VALUES (8, 'Fauchet', 'null', 'muriellefauchet@hotmail.fr', '1234', 'user');
INSERT INTO public.utilisateurs (id, nom, prenom, email, motdepasse, role) VALUES (10, 'Cook', 'null', 'thiernohabibbah@gmail.com', 'aeoneflux****', 'user');
INSERT INTO public.utilisateurs (id, nom, prenom, email, motdepasse, role) VALUES (11, 'www', 'null', 'zappelini@hotmail.fr', '1234', 'user');
INSERT INTO public.utilisateurs (id, nom, prenom, email, motdepasse, role) VALUES (12, 'Le Sommaire', 'null', 'eleansom@gmail.com', '1234', 'user');