UPDATE public.livre SET auteur = 'George Orwell', titre = 'LECUME DES JOURS', nombredepages = 200, nombreexemplaire = 9, categorie = 'null', nombredepage = null WHERE id = 91;
UPDATE public.livre SET auteur = 'Charlotte Bronte', titre = 'JANE EYRE', nombredepages = 300, nombreexemplaire = 9, categorie = 'null', nombredepage = null WHERE id = 92;
UPDATE public.livre SET auteur = 'Virginia Woolf', titre = 'MRS DALLOWAY', nombredepages = 300, nombreexemplaire = 9, categorie = 'null', nombredepage = null WHERE id = 93;
UPDATE public.livre SET auteur = 'Alain Damasio', titre = 'La Horde du Contrevent ', nombredepages = 250, nombreexemplaire = 1, categorie = 'Roman', nombredepage = null WHERE id = 169;
UPDATE public.livre SET auteur = 'George Orwell', titre = 'LECUME DES JOURS', nombredepages = 200, nombreexemplaire = 8, categorie = 'null', nombredepage = null WHERE id = 170;
UPDATE public.livre SET auteur = 'Roberta', titre = 'Les passions de papa', nombredepages = 250, nombreexemplaire = 0, categorie = 'Roman', nombredepage = null WHERE id = 104;
UPDATE public.livre SET auteur = 'Robert Warrent', titre = 'Les fous du roi', nombredepages = 250, nombreexemplaire = 9, categorie = 'Roman', nombredepage = null WHERE id = 177;
UPDATE public.livre SET auteur = 'Brest Easton ellis', titre = 'AMERICAN PSYCHO', nombredepages = 500, nombreexemplaire = 10, categorie = null, nombredepage = null WHERE id = 19;
UPDATE public.livre SET auteur = 'Trunan Capote', titre = 'DE SANG FROID', nombredepages = 400, nombreexemplaire = 15, categorie = null, nombredepage = null WHERE id = 20;
UPDATE public.livre SET auteur = 'Joris-Karl Huysmans', titre = 'LÀ-BAS', nombredepages = 300, nombreexemplaire = 15, categorie = null, nombredepage = null WHERE id = 21;
UPDATE public.livre SET auteur = 'Johann Wolfgang', titre = 'FAUST', nombredepages = 450, nombreexemplaire = 15, categorie = null, nombredepage = null WHERE id = 22;
UPDATE public.livre SET auteur = 'Tenessee Williams', titre = 'UN TRAMWAY NOMMÉ DÉSIR', nombredepages = 500, nombreexemplaire = 15, categorie = null, nombredepage = null WHERE id = 23;
UPDATE public.livre SET auteur = 'Albert Camus', titre = 'LA PESTE', nombredepages = 400, nombreexemplaire = 15, categorie = null, nombredepage = null WHERE id = 24;
UPDATE public.livre SET auteur = 'Romain Gary', titre = 'LA VIE DEVANT SOIT', nombredepages = 600, nombreexemplaire = 15, categorie = null, nombredepage = null WHERE id = 25;
UPDATE public.livre SET auteur = 'Edmon Rostand', titre = 'CRYNO DE BERGERAC', nombredepages = 400, nombreexemplaire = 15, categorie = null, nombredepage = null WHERE id = 26;
UPDATE public.livre SET auteur = 'Franz Kafka', titre = 'LA METAMORPHOSE', nombredepages = 300, nombreexemplaire = 15, categorie = null, nombredepage = null WHERE id = 27;
UPDATE public.livre SET auteur = 'J.R.R Tolkien', titre = 'LE SEIGNEUR DES ANNEAUX', nombredepages = 700, nombreexemplaire = 15, categorie = null, nombredepage = null WHERE id = 28;
UPDATE public.livre SET auteur = 'George Orwell', titre = 'LECUME DES JOURS', nombredepages = 200, nombreexemplaire = 10, categorie = null, nombredepage = null WHERE id = 30;
UPDATE public.livre SET auteur = 'Charlotte Bronte', titre = 'JANE EYRE', nombredepages = 300, nombreexemplaire = 10, categorie = null, nombredepage = null WHERE id = 31;
UPDATE public.livre SET auteur = 'Virginia Woolf', titre = 'MRS DALLOWAY', nombredepages = 300, nombreexemplaire = 10, categorie = null, nombredepage = null WHERE id = 32;
UPDATE public.livre SET auteur = 'Brest Easton ellis', titre = 'AMERICAN PSYCHO', nombredepages = 500, nombreexemplaire = 9, categorie = 'null', nombredepage = null WHERE id = 36;
UPDATE public.livre SET auteur = 'Trunan Capote', titre = 'DE SANG FROID', nombredepages = 400, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 37;
UPDATE public.livre SET auteur = 'Joris-Karl Huysmans', titre = 'LÀ-BAS', nombredepages = 300, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 38;
UPDATE public.livre SET auteur = 'Johann Wolfgang', titre = 'FAUST', nombredepages = 450, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 39;
UPDATE public.livre SET auteur = 'Tenessee Williams', titre = 'UN TRAMWAY NOMMÉ DÉSIR', nombredepages = 500, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 40;
UPDATE public.livre SET auteur = 'Albert Camus', titre = 'LA PESTE', nombredepages = 400, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 41;
UPDATE public.livre SET auteur = 'Romain Gary', titre = 'LA VIE DEVANT SOIT', nombredepages = 600, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 42;
UPDATE public.livre SET auteur = 'Edmon Rostand', titre = 'CRYNO DE BERGERAC', nombredepages = 400, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 43;
UPDATE public.livre SET auteur = 'Franz Kafka', titre = 'LA METAMORPHOSE', nombredepages = 300, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 44;
UPDATE public.livre SET auteur = 'J.R.R Tolkien', titre = 'LE SEIGNEUR DES ANNEAUX', nombredepages = 700, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 45;
UPDATE public.livre SET auteur = 'George Orwell', titre = 'LECUME DES JOURS', nombredepages = 200, nombreexemplaire = 9, categorie = 'null', nombredepage = null WHERE id = 46;
UPDATE public.livre SET auteur = 'Charlotte Bronte', titre = 'JANE EYRE', nombredepages = 300, nombreexemplaire = 9, categorie = 'null', nombredepage = null WHERE id = 47;
UPDATE public.livre SET auteur = 'Virginia Woolf', titre = 'MRS DALLOWAY', nombredepages = 300, nombreexemplaire = 9, categorie = 'null', nombredepage = null WHERE id = 48;
UPDATE public.livre SET auteur = 'Brest Easton ellis', titre = 'AMERICAN PSYCHO', nombredepages = 500, nombreexemplaire = 9, categorie = 'null', nombredepage = null WHERE id = 51;
UPDATE public.livre SET auteur = 'Trunan Capote', titre = 'DE SANG FROID', nombredepages = 400, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 52;
UPDATE public.livre SET auteur = 'Johann Wolfgang', titre = 'FAUST', nombredepages = 450, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 54;
UPDATE public.livre SET auteur = 'Tenessee Williams', titre = 'UN TRAMWAY NOMMÉ DÉSIR', nombredepages = 500, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 55;
UPDATE public.livre SET auteur = 'Albert Camus', titre = 'LA PESTE', nombredepages = 400, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 56;
UPDATE public.livre SET auteur = 'Romain Gary', titre = 'LA VIE DEVANT SOIT', nombredepages = 600, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 57;
UPDATE public.livre SET auteur = 'Edmon Rostand', titre = 'CRYNO DE BERGERAC', nombredepages = 400, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 58;
UPDATE public.livre SET auteur = 'Franz Kafka', titre = 'LA METAMORPHOSE', nombredepages = 300, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 59;
UPDATE public.livre SET auteur = 'J.R.R Tolkien', titre = 'LE SEIGNEUR DES ANNEAUX', nombredepages = 700, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 60;
UPDATE public.livre SET auteur = 'George Orwell', titre = 'LECUME DES JOURS', nombredepages = 200, nombreexemplaire = 9, categorie = 'null', nombredepage = null WHERE id = 61;
UPDATE public.livre SET auteur = 'Charlotte Bronte', titre = 'JANE EYRE', nombredepages = 300, nombreexemplaire = 9, categorie = 'null', nombredepage = null WHERE id = 62;
UPDATE public.livre SET auteur = 'Virginia Woolf', titre = 'MRS DALLOWAY', nombredepages = 300, nombreexemplaire = 9, categorie = 'null', nombredepage = null WHERE id = 63;
UPDATE public.livre SET auteur = 'Brest Easton ellis', titre = 'AMERICAN PSYCHO', nombredepages = 500, nombreexemplaire = 9, categorie = 'null', nombredepage = null WHERE id = 66;
UPDATE public.livre SET auteur = 'Trunan Capote', titre = 'DE SANG FROID', nombredepages = 400, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 67;
UPDATE public.livre SET auteur = 'Joris-Karl Huysmans', titre = 'LÀ-BAS', nombredepages = 300, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 68;
UPDATE public.livre SET auteur = 'Johann Wolfgang', titre = 'FAUST', nombredepages = 450, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 69;
UPDATE public.livre SET auteur = 'Tenessee Williams', titre = 'UN TRAMWAY NOMMÉ DÉSIR', nombredepages = 500, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 70;
UPDATE public.livre SET auteur = 'Albert Camus', titre = 'LA PESTE', nombredepages = 400, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 71;
UPDATE public.livre SET auteur = 'Romain Gary', titre = 'LA VIE DEVANT SOIT', nombredepages = 600, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 72;
UPDATE public.livre SET auteur = 'Edmon Rostand', titre = 'CRYNO DE BERGERAC', nombredepages = 400, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 73;
UPDATE public.livre SET auteur = 'Franz Kafka', titre = 'LA METAMORPHOSE', nombredepages = 300, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 74;
UPDATE public.livre SET auteur = 'Hans Christian Andersen', titre = 'La reine des neiges', nombredepages = 250, nombreexemplaire = 1, categorie = 'Roman', nombredepage = null WHERE id = 198;
UPDATE public.livre SET auteur = 'Romain Gary', titre = 'LA VIE DEVANT SOIT', nombredepages = 600, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 87;
UPDATE public.livre SET auteur = 'Edmon Rostand', titre = 'CRYNO DE BERGERAC', nombredepages = 400, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 88;
UPDATE public.livre SET auteur = 'Franz Kafka', titre = 'LA METAMORPHOSE', nombredepages = 300, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 89;
UPDATE public.livre SET auteur = 'J.R.R Tolkien', titre = 'LE SEIGNEUR DES ANNEAUX', nombredepages = 700, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 90;
UPDATE public.livre SET auteur = 'Joris-Karl Huysmans', titre = 'LÀ-BAS', nombredepages = 300, nombreexemplaire = 14, categorie = 'null', nombredepage = null WHERE id = 144;