
package com.opendevup.client2.client2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BibliothequeService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8686/BibliotequeVilleWS?wsdl")
public class BibliothequeService
    extends Service
{

    private final static URL BIBLIOTHEQUESERVICE_WSDL_LOCATION;
    private final static WebServiceException BIBLIOTHEQUESERVICE_EXCEPTION;
    private final static QName BIBLIOTHEQUESERVICE_QNAME = new QName("http://service/", "BibliothequeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8686/BibliotequeVilleWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BIBLIOTHEQUESERVICE_WSDL_LOCATION = url;
        BIBLIOTHEQUESERVICE_EXCEPTION = e;
    }

    public BibliothequeService() {
        super(__getWsdlLocation(), BIBLIOTHEQUESERVICE_QNAME);
    }

    public BibliothequeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BIBLIOTHEQUESERVICE_QNAME, features);
    }

    public BibliothequeService(URL wsdlLocation) {
        super(wsdlLocation, BIBLIOTHEQUESERVICE_QNAME);
    }

    public BibliothequeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BIBLIOTHEQUESERVICE_QNAME, features);
    }

    public BibliothequeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BibliothequeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BibliotequeVilleWS
     */
    @WebEndpoint(name = "BibliotequeVilleWSPort")
    public BibliotequeVilleWS getBibliotequeVilleWSPort() {
        return super.getPort(new QName("http://service/", "BibliotequeVilleWSPort"), BibliotequeVilleWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BibliotequeVilleWS
     */
    @WebEndpoint(name = "BibliotequeVilleWSPort")
    public BibliotequeVilleWS getBibliotequeVilleWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "BibliotequeVilleWSPort"), BibliotequeVilleWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BIBLIOTHEQUESERVICE_EXCEPTION!= null) {
            throw BIBLIOTHEQUESERVICE_EXCEPTION;
        }
        return BIBLIOTHEQUESERVICE_WSDL_LOCATION;
    }

}
