
package client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BibliotequeVilleWS", targetNamespace = "http://wsService.ws.oc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BibliotequeVilleWS {


    /**
     * 
     * @param nomutilisateur
     * @param datedebut
     * @param datefin
     * @param prenom
     * @param titrelivre
     * @param email
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "reservation", targetNamespace = "http://wsService.ws.oc.com/", className = "client.Reservation")
    @ResponseWrapper(localName = "reservationResponse", targetNamespace = "http://wsService.ws.oc.com/", className = "client.ReservationResponse")
    @Action(input = "http://wsService.ws.oc.com/BibliotequeVilleWS/reservationRequest", output = "http://wsService.ws.oc.com/BibliotequeVilleWS/reservationResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://wsService.ws.oc.com/BibliotequeVilleWS/reservation/Fault/IOException")
    })
    public void reservation(
        @WebParam(name = "Nomutilisateur", targetNamespace = "")
        String nomutilisateur,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "titrelivre", targetNamespace = "")
        String titrelivre,
        @WebParam(name = "datedebut", targetNamespace = "")
        String datedebut,
        @WebParam(name = "datefin", targetNamespace = "")
        String datefin,
        @WebParam(name = "email", targetNamespace = "")
        String email)
        throws IOException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<client.Livre>
     * @throws IOException_Exception
     */
    @WebMethod(operationName = "Listedeslivres")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Listedeslivres", targetNamespace = "http://wsService.ws.oc.com/", className = "client.Listedeslivres")
    @ResponseWrapper(localName = "ListedeslivresResponse", targetNamespace = "http://wsService.ws.oc.com/", className = "client.ListedeslivresResponse")
    @Action(input = "http://wsService.ws.oc.com/BibliotequeVilleWS/ListedeslivresRequest", output = "http://wsService.ws.oc.com/BibliotequeVilleWS/ListedeslivresResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://wsService.ws.oc.com/BibliotequeVilleWS/Listedeslivres/Fault/IOException")
    })
    public List<Livre> listedeslivres()
        throws IOException_Exception
    ;

    /**
     * 
     * @param email
     * @return
     *     returns java.util.List<java.lang.Object>
     * @throws IOException_Exception
     */
    @WebMethod(operationName = "USerReservation")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "USerReservation", targetNamespace = "http://wsService.ws.oc.com/", className = "client.USerReservation")
    @ResponseWrapper(localName = "USerReservationResponse", targetNamespace = "http://wsService.ws.oc.com/", className = "client.USerReservationResponse")
    @Action(input = "http://wsService.ws.oc.com/BibliotequeVilleWS/USerReservationRequest", output = "http://wsService.ws.oc.com/BibliotequeVilleWS/USerReservationResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://wsService.ws.oc.com/BibliotequeVilleWS/USerReservation/Fault/IOException")
    })
    public List<Object> uSerReservation(
        @WebParam(name = "email", targetNamespace = "")
        String email)
        throws IOException_Exception
    ;

    /**
     * 
     * @param motdepasse
     * @param nom
     * @param prenom
     * @param email
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "inscription", targetNamespace = "http://wsService.ws.oc.com/", className = "client.Inscription")
    @ResponseWrapper(localName = "inscriptionResponse", targetNamespace = "http://wsService.ws.oc.com/", className = "client.InscriptionResponse")
    @Action(input = "http://wsService.ws.oc.com/BibliotequeVilleWS/inscriptionRequest", output = "http://wsService.ws.oc.com/BibliotequeVilleWS/inscriptionResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://wsService.ws.oc.com/BibliotequeVilleWS/inscription/Fault/IOException")
    })
    public void inscription(
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "motdepasse", targetNamespace = "")
        String motdepasse)
        throws IOException_Exception
    ;

    /**
     * 
     * @param motdepasse
     * @param email
     * @return
     *     returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "connexion", targetNamespace = "http://wsService.ws.oc.com/", className = "client.Connexion")
    @ResponseWrapper(localName = "connexionResponse", targetNamespace = "http://wsService.ws.oc.com/", className = "client.ConnexionResponse")
    @Action(input = "http://wsService.ws.oc.com/BibliotequeVilleWS/connexionRequest", output = "http://wsService.ws.oc.com/BibliotequeVilleWS/connexionResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://wsService.ws.oc.com/BibliotequeVilleWS/connexion/Fault/IOException")
    })
    public boolean connexion(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "motdepasse", targetNamespace = "")
        String motdepasse)
        throws IOException_Exception
    ;

    /**
     * 
     * @param datedebut
     * @param datefin
     * @param nom
     * @param prenom
     * @param titrelivre
     * @param email
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "prolongerpret", targetNamespace = "http://wsService.ws.oc.com/", className = "client.Prolongerpret")
    @ResponseWrapper(localName = "prolongerpretResponse", targetNamespace = "http://wsService.ws.oc.com/", className = "client.ProlongerpretResponse")
    @Action(input = "http://wsService.ws.oc.com/BibliotequeVilleWS/prolongerpretRequest", output = "http://wsService.ws.oc.com/BibliotequeVilleWS/prolongerpretResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://wsService.ws.oc.com/BibliotequeVilleWS/prolongerpret/Fault/IOException")
    })
    public void prolongerpret(
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "titrelivre", targetNamespace = "")
        String titrelivre,
        @WebParam(name = "datedebut", targetNamespace = "")
        String datedebut,
        @WebParam(name = "datefin", targetNamespace = "")
        String datefin,
        @WebParam(name = "email", targetNamespace = "")
        String email)
        throws IOException_Exception
    ;

    /**
     * 
     * @param titrelivre
     * @return
     *     returns client.Livre
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "trouverlivre", targetNamespace = "http://wsService.ws.oc.com/", className = "client.Trouverlivre")
    @ResponseWrapper(localName = "trouverlivreResponse", targetNamespace = "http://wsService.ws.oc.com/", className = "client.TrouverlivreResponse")
    @Action(input = "http://wsService.ws.oc.com/BibliotequeVilleWS/trouverlivreRequest", output = "http://wsService.ws.oc.com/BibliotequeVilleWS/trouverlivreResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://wsService.ws.oc.com/BibliotequeVilleWS/trouverlivre/Fault/IOException")
    })
    public Livre trouverlivre(
        @WebParam(name = "titrelivre", targetNamespace = "")
        String titrelivre)
        throws IOException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<client.Utilisateur>
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listUser", targetNamespace = "http://wsService.ws.oc.com/", className = "client.ListUser")
    @ResponseWrapper(localName = "listUserResponse", targetNamespace = "http://wsService.ws.oc.com/", className = "client.ListUserResponse")
    @Action(input = "http://wsService.ws.oc.com/BibliotequeVilleWS/listUserRequest", output = "http://wsService.ws.oc.com/BibliotequeVilleWS/listUserResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://wsService.ws.oc.com/BibliotequeVilleWS/listUser/Fault/IOException")
    })
    public List<Utilisateur> listUser()
        throws IOException_Exception
    ;

    /**
     * 
     * @param motdepasse
     * @param email
     * @return
     *     returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "connexionEquipe", targetNamespace = "http://wsService.ws.oc.com/", className = "client.ConnexionEquipe")
    @ResponseWrapper(localName = "connexionEquipeResponse", targetNamespace = "http://wsService.ws.oc.com/", className = "client.ConnexionEquipeResponse")
    @Action(input = "http://wsService.ws.oc.com/BibliotequeVilleWS/connexionEquipeRequest", output = "http://wsService.ws.oc.com/BibliotequeVilleWS/connexionEquipeResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://wsService.ws.oc.com/BibliotequeVilleWS/connexionEquipe/Fault/IOException")
    })
    public boolean connexionEquipe(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "motdepasse", targetNamespace = "")
        String motdepasse)
        throws IOException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<client.Pret>
     * @throws IOException_Exception
     */
    @WebMethod(operationName = "ListPret")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ListPret", targetNamespace = "http://wsService.ws.oc.com/", className = "client.ListPret")
    @ResponseWrapper(localName = "ListPretResponse", targetNamespace = "http://wsService.ws.oc.com/", className = "client.ListPretResponse")
    @Action(input = "http://wsService.ws.oc.com/BibliotequeVilleWS/ListPretRequest", output = "http://wsService.ws.oc.com/BibliotequeVilleWS/ListPretResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://wsService.ws.oc.com/BibliotequeVilleWS/ListPret/Fault/IOException")
    })
    public List<Pret> listPret()
        throws IOException_Exception
    ;

    /**
     * 
     * @param email
     * @param titrelivre
     * @throws IOException_Exception
     */
    @WebMethod(operationName = "Retour")
    @RequestWrapper(localName = "Retour", targetNamespace = "http://wsService.ws.oc.com/", className = "client.Retour")
    @ResponseWrapper(localName = "RetourResponse", targetNamespace = "http://wsService.ws.oc.com/", className = "client.RetourResponse")
    @Action(input = "http://wsService.ws.oc.com/BibliotequeVilleWS/RetourRequest", output = "http://wsService.ws.oc.com/BibliotequeVilleWS/RetourResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://wsService.ws.oc.com/BibliotequeVilleWS/Retour/Fault/IOException")
    })
    public void retour(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "titrelivre", targetNamespace = "")
        String titrelivre)
        throws IOException_Exception
    ;

}
